In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
dataset = pd.read_excel('C://Users//S1130863//Downloads/diss/testing_lbwo.xlsx')

In [69]:
years = sorted(dataset.loc[:,'Observation Year'].unique().tolist())
years

[1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001]

In [70]:
import random
#selectedyears = random.sample(years,6)
selectedyears = years[:6]
selectedyears

[1993, 1994, 1995, 1996, 1998, 1999]

In [71]:
data_train = dataset[dataset['Observation Year'].isin(selectedyears)]
data_test = dataset[~dataset['Observation Year'].isin(selectedyears)]

In [72]:
X_train = data_train.loc[:, ['MAXT','MINT','RH1','RH2','RF','WS','SSH','EVP','Apriori-rule']]
X_test = data_test.loc[:, ['MAXT','MINT','RH1','RH2','RF','WS','SSH','EVP','Apriori-rule']]
y_train = data_train.loc[:, ['LB_binary']]
y_test = data_test.loc[:, ['LB_binary']]

In [73]:
X_train

MAXT  MINT   RH1   RH2    RF   WS   SSH  EVP  Apriori-rule
0    29.1  12.8  75.9  29.6   0.0  2.1   9.6  3.2             0
1    31.1  13.1  72.6  27.3   0.0  1.7  10.2  3.2             0
2    30.7  13.1  75.3  28.3   0.0  1.8   9.9  3.0             0
3    30.3  11.4  74.0  29.6   0.0  1.7   9.9  3.1             0
4    30.5  12.7  76.3  27.1   0.0  2.2  10.0  3.1             0
..    ...   ...   ...   ...   ...  ...   ...  ...           ...
357  28.6  22.8  87.0  67.0   1.9  5.4   4.4  3.4             1
358  31.4  23.0  80.1  52.6   1.8  4.4   7.0  5.3             1
359  31.7  23.1  93.6  60.4  23.4  1.9   5.7  2.9             1
360  31.1  22.9  89.6  60.6  14.6  3.0   8.6  3.7             1
361  31.5  22.4  92.3  52.3   8.4  2.3   7.4  3.6             1

[312 rows x 9 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
X_train.iloc[:,:8] = sc.fit_transform(X_train.iloc[:,:8])
X_test.iloc[:,:8] = sc.transform(X_test.iloc[:,:8])

In [25]:
X_test

MAXT      MINT       RH1       RH2        RF        WS       SSH  \
73  -0.962261 -1.503431  0.234385 -0.602145 -0.543958 -0.937585  0.575039   
74   2.122908  0.829144 -2.304501 -0.971822  0.657143 -0.237459  1.037732   
75   1.053051  1.235740 -1.507089 -0.432624 -0.493118  0.596514  1.191963   
76   0.779367  1.150140 -1.057972 -0.144643 -0.299289  0.071420  0.343693   
77   0.854008  1.107341 -0.407211  0.131083  0.250421  0.225860  0.266578   
..        ...       ...       ...       ...       ...       ...       ...   
411 -0.340251 -0.112446  0.729330  0.039174 -0.543958 -0.484562 -0.003326   
412 -0.464653 -0.005447 -0.407211  0.296519 -0.543958 -0.515450  0.305135   
413 -0.564175 -0.968437  0.509355 -0.230425 -0.543958 -0.886105  0.382251   
414 -0.663697 -2.209623 -0.223898 -1.051476 -0.543958 -0.978769  0.883501   
415 -0.514414 -1.760228  0.417698 -0.677714 -0.543958 -0.947881  0.729270   

          EVP  Apriori-rule  
73  -0.668809             0  
74   1.502817             0  
75   1.391134             0  
76   0.758260             0  
77   0.832715             0  
..        ...           ...  
411 -0.358577             1  
412 -0.284121             1  
413 -0.619172             1  
414 -0.619172             0  
415 -0.656400             0  

[104 rows x 9 columns]

In [58]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

C:\Users\S1130863\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\S1130863\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[48  4]
 [ 0  0]]


0.9230769230769231

In [60]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.0

In [26]:
import tensorflow as tf

In [61]:
ann = tf.keras.models.Sequential()

In [62]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [63]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [64]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [65]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [66]:
ann.fit(X_train, y_train, batch_size = 26, epochs = 100)

Epoch 1/100
14/14 [==============================] - 1s 4ms/step - loss: 1.3632 - accuracy: 0.6676
Epoch 2/100
14/14 [==============================] - 0s 5ms/step - loss: 0.9819 - accuracy: 0.6511
Epoch 3/100
14/14 [==============================] - 0s 3ms/step - loss: 0.7696 - accuracy: 0.6978
Epoch 4/100
14/14 [==============================] - 0s 4ms/step - loss: 0.6040 - accuracy: 0.7143
Epoch 5/100
14/14 [==============================] - 0s 4ms/step - loss: 0.4948 - accuracy: 0.7500
Epoch 6/100
14/14 [==============================] - 0s 4ms/step - loss: 0.4546 - accuracy: 0.7912
Epoch 7/100
14/14 [==============================] - 0s 4ms/step - loss: 0.4211 - accuracy: 0.8187
Epoch 8/100
14/14 [==============================] - 0s 4ms/step - loss: 0.3835 - accuracy: 0.8269
Epoch 9/100
14/14 [==============================] - 0s 4ms/step - loss: 0.3635 - accuracy: 0.8462
Epoch 10/100
14/14 [==============================] - 0s 4ms/step - loss: 0.3673 - accuracy: 0.8269
Epoch 11/

14/14 [==============================] - 0s 4ms/step - loss: 0.2409 - accuracy: 0.8709
Epoch 84/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2332 - accuracy: 0.8819
Epoch 85/100
14/14 [==============================] - 0s 3ms/step - loss: 0.2165 - accuracy: 0.9011
Epoch 86/100
14/14 [==============================] - 0s 3ms/step - loss: 0.2102 - accuracy: 0.9038
Epoch 87/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2103 - accuracy: 0.9093
Epoch 88/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2138 - accuracy: 0.9121
Epoch 89/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2257 - accuracy: 0.8764
Epoch 90/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2163 - accuracy: 0.9038
Epoch 91/100
14/14 [==============================] - 0s 3ms/step - loss: 0.2418 - accuracy: 0.8874
Epoch 92/100
14/14 [==============================] - 0s 4ms/step - loss: 0.2398 - accuracy: 0.8791
Epoch 93/100


In [67]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

2/2 [==============================] - 0s 6ms/step


In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[49  3]
 [ 0  0]]


0.9423076923076923

In [44]:
cnn = tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv1D(filters=32, kernel_size=4, activation='relu', input_shape=[9, 1]))
#cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
#cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
#cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=12, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=12, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn.fit(X_train,y_train, epochs = 25)

Epoch 1/25
10/10 [==============================] - 1s 4ms/step - loss: 0.6670 - accuracy: 0.7212
Epoch 2/25
10/10 [==============================] - 0s 4ms/step - loss: 0.5923 - accuracy: 0.8269
Epoch 3/25
10/10 [==============================] - 0s 4ms/step - loss: 0.5150 - accuracy: 0.8269
Epoch 4/25
10/10 [==============================] - 0s 3ms/step - loss: 0.4340 - accuracy: 0.8269
Epoch 5/25
10/10 [==============================] - 0s 4ms/step - loss: 0.3688 - accuracy: 0.8269
Epoch 6/25
10/10 [==============================] - 0s 4ms/step - loss: 0.3214 - accuracy: 0.8269
Epoch 7/25
10/10 [==============================] - 0s 4ms/step - loss: 0.2900 - accuracy: 0.8301
Epoch 8/25
10/10 [==============================] - 0s 4ms/step - loss: 0.2703 - accuracy: 0.8462
Epoch 9/25
10/10 [==============================] - 0s 3ms/step - loss: 0.2552 - accuracy: 0.8654
Epoch 10/25
10/10 [==============================] - 0s 4ms/step - loss: 0.2461 - accuracy: 0.8782
Epoch 11/25
10/10 [

In [45]:
y_pred = cnn.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

4/4 [==============================] - 0s 3ms/step
[[86  6]
 [ 8  4]]


0.8653846153846154